/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import javax.swing.JOptionPane;
import java.util.List;

/**
 *
 * @author Nicolas
 */
public class AlugueisPanel extends javax.swing.JPanel {
    private dao.AluguelDAO aluguelDAO = new dao.AluguelDAO();
    private dao.JogoDAO jogoDAO = new dao.JogoDAO(); // Para carregar o ComboBox
    /**
     * Creates new form AlugueisPanel
     */
    public AlugueisPanel() {
        initComponents();
        carregarJogosCombo();
        carregarAlugueis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlForm = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDias = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtContato = new javax.swing.JTextField();
        cmbJogo = new javax.swing.JComboBox<>();
        scrAlugueis = new javax.swing.JScrollPane();
        tblAlugueis = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnDevolver = new javax.swing.JButton();

        pnlForm.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("CPF");

        txtCPF.addActionListener(this::txtCPFActionPerformed);

        jLabel5.setText("Endereço*");

        txtEndereco.addActionListener(this::txtEnderecoActionPerformed);

        jLabel6.setText("Jogo");

        jLabel1.setText("Novo Jogo");

        jLabel7.setText("Dias");

        jLabel2.setText("Nome");

        txtDias.addActionListener(this::txtDiasActionPerformed);

        txtNome.addActionListener(this::txtNomeActionPerformed);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(this::btnCadastrarActionPerformed);

        jLabel3.setText("Contato*");

        txtContato.addActionListener(this::txtContatoActionPerformed);

        javax.swing.GroupLayout pnlFormLayout = new javax.swing.GroupLayout(pnlForm);
        pnlForm.setLayout(pnlFormLayout);
        pnlFormLayout.setHorizontalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(576, 576, 576))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlFormLayout.createSequentialGroup()
                            .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(cmbJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7)
                                .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3)
                                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtContato, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFormLayout.setVerticalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrar)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tblAlugueis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Jogo", "Início", "Devolução", "Status"
            }
        ));
        scrAlugueis.setViewportView(tblAlugueis);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnDevolver.setText("Marcar como devolvido");
        btnDevolver.addActionListener(this::btnDevolverActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnDevolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDevolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrAlugueis, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrAlugueis, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void txtDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiasActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        String nome     = txtNome.getText().trim();
        String contato  = txtContato.getText().trim();
        String cpf      = txtCPF.getText().trim();
        String endereco = txtEndereco.getText().trim();
        String diasS    = txtDias.getText().trim();
        model.Jogo jogo = (model.Jogo) cmbJogo.getSelectedItem();

        if (nome.isEmpty() || contato.isEmpty() || endereco.isEmpty() || jogo == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Preencha os campos obrigatórios (*).", "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            int dias = diasS.isEmpty() ? 7 : Integer.parseInt(diasS);
            if (jogo.getQuantidadeEstoque() <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Jogo sem estoque.", "Aviso",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            util.DataStore.getInstance().addAluguel(
                new model.Aluguel(0, nome, contato, cpf, endereco,
                    jogo, dias, java.time.LocalDate.now()));
            jogo.setQuantidadeEstoque(jogo.getQuantidadeEstoque() - 1);
            util.DataStore.getInstance().addTransacao(new model.Transacao(0,
                "Aluguel – " + jogo.getNome(), model.Transacao.Tipo.ENTRADA,
                jogo.getValorAluguel(),
                java.time.LocalDate.now().format(
                    java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy"))));
        javax.swing.JOptionPane.showMessageDialog(this,
            "Aluguel cadastrado!", "Sucesso",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
        txtNome.setText(""); txtContato.setText("");
        txtCPF.setText(""); txtEndereco.setText(""); txtDias.setText("7");
        carregarJogosCombo();
        carregarAlugueis();
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Número de dias inválido.", "Erro",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContatoActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
                                           
        int row = tblAlugueis.getSelectedRow();
        if (row < 0) return;

        // Pegamos a lista atual do banco para achar o objeto
        model.Aluguel a = aluguelDAO.listarTodos().get(row);

        if (a.isDevolvido()) {
            JOptionPane.showMessageDialog(this, "Já devolvido.");
            return;
        }

        // Atualiza no banco: Status e Devolve o item ao estoque
        aluguelDAO.registrarDevolucao(a.getId(), a.getJogo().getId());

        JOptionPane.showMessageDialog(this, "Devolução concluída!");
        carregarAlugueis();
        carregarJogosCombo();

    }//GEN-LAST:event_btnDevolverActionPerformed

    private void carregarJogosCombo() {
        try {
        cmbJogo.removeAllItems();
        List<model.Jogo> jogos = jogoDAO.listarTodos();
        
        if (jogos != null) {
            for (model.Jogo j : jogos) {
                if (j.getQuantidadeEstoque() > 0) {
                    cmbJogo.addItem(j);
                }
            }
        }
    } catch (Exception e) {
        // Isso vai te mostrar na tela qual o erro exato do SQL
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Erro ao carregar jogos do banco: " + e.getMessage(), 
            "Erro de Banco de Dados", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    }   

private void carregarAlugueis() {
    javax.swing.table.DefaultTableModel mdl =
        (javax.swing.table.DefaultTableModel) tblAlugueis.getModel();
    mdl.setRowCount(0);
    for (model.Aluguel a : util.DataStore.getInstance().getAlugueis()) {
        String status = a.isDevolvido() ? "Devolvido"
            : (java.time.LocalDate.now().isAfter(a.getDataDevolucao())
                ? "Atrasado!" : "Ativo");
        mdl.addRow(new Object[]{
            a.getId(), a.getNomeCliente(), a.getJogo().getNome(),
            a.getDataInicio(), a.getDataDevolucao(), status
        });
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnDevolver;
    private javax.swing.JComboBox<model.Jogo> cmbJogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JScrollPane scrAlugueis;
    private javax.swing.JTable tblAlugueis;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtContato;
    private javax.swing.JTextField txtDias;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
