/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import java.sql.SQLException;

/**
 *
 * @author Nicolas
 */
public class JogosPanel extends javax.swing.JPanel {

    private model.Jogo jogoSelecionado = null;    
    private dao.JogoDAO jogoDAO = new dao.JogoDAO();

    public JogosPanel() {
        initComponents();
        carregarJogos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrJogos = new javax.swing.JScrollPane();
        tblJogos = new javax.swing.JTable();
        pnlForm = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtPlataforma = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEstoque = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDias = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnExcluir = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        scrJogos.setBackground(new java.awt.Color(255, 255, 255));

        tblJogos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Jogo", "Plataforma", "Ano"
            }
        ));
        scrJogos.setViewportView(tblJogos);

        pnlForm.setBackground(new java.awt.Color(255, 255, 255));
        pnlForm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel4.setText("Plataforma");

        txtPlataforma.addActionListener(this::txtPlataformaActionPerformed);

        jLabel5.setText("Valor do Aluguel");

        txtValor.addActionListener(this::txtValorActionPerformed);

        jLabel6.setText("Quantidade em Estoque");

        txtEstoque.addActionListener(this::txtEstoqueActionPerformed);

        jLabel1.setText("Novo Jogo");

        jLabel7.setText("Dias de aluguel padrão");

        jLabel2.setText("Nome");

        txtDias.addActionListener(this::txtDiasActionPerformed);

        txtNome.addActionListener(this::txtNomeActionPerformed);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(this::btnCadastrarActionPerformed);

        jLabel3.setText("Ano");

        txtAno.addActionListener(this::txtAnoActionPerformed);

        btnExcluir.setText("Excluir Jogo");
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        javax.swing.GroupLayout pnlFormLayout = new javax.swing.GroupLayout(pnlForm);
        pnlForm.setLayout(pnlFormLayout);
        pnlFormLayout.setHorizontalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormLayout.createSequentialGroup()
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCadastrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFormLayout.createSequentialGroup()
                                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtPlataforma, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtEstoque, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                        .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(txtValor)
                                    .addComponent(txtDias)
                                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(32, 32, 32))
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addComponent(btnExcluir)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlFormLayout.setVerticalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCadastrar)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrJogos, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrJogos, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlataformaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlataformaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlataformaActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void txtEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstoqueActionPerformed

    private void txtDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiasActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        String nome = txtNome.getText().trim();
        String anoS = txtAno.getText().trim();
        String plat = txtPlataforma.getText().trim();

        if (nome.isEmpty() || anoS.isEmpty() || plat.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Preencha Nome, Ano e Plataforma.", "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            int    ano   = Integer.parseInt(anoS);
            double valor = txtValor.getText().trim().isEmpty() ? 0
            : Double.parseDouble(txtValor.getText().trim().replace(",", "."));
            int    est   = txtEstoque.getText().trim().isEmpty() ? 0
            : Integer.parseInt(txtEstoque.getText().trim());
            int    dias  = txtDias.getText().trim().isEmpty() ? 7
            : Integer.parseInt(txtDias.getText().trim());

            try {
            // ... (suas conversões de Integer.parseInt e Double.parseDouble)

            // Criando o objeto com os dados dos campos
            model.Jogo novoJogo = new model.Jogo(0, nome, ano, plat, valor, dias, est);

            // Agora o DAO aceita o objeto 'novoJogo' como único argumento
            jogoDAO.cadastrar(novoJogo); 

            javax.swing.JOptionPane.showMessageDialog(this, "Jogo cadastrado no MySQL!");

            // Limpa os campos e recarrega a tabela
            txtNome.setText(""); txtAno.setText(""); txtPlataforma.setText("");
            txtValor.setText(""); txtEstoque.setText(""); txtDias.setText("");
            carregarJogos();

            } catch (SQLException ex) {
                javax.swing.JOptionPane.showMessageDialog(this, "Erro no Banco: " + ex.getMessage());
            }   
            
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Verifique os campos numéricos.", "Erro",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

                                                 
    int row = tblJogos.getSelectedRow();
    
    // Verifica se tem algo selecionado
    if (row < 0) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Selecione um jogo na tabela para excluir.", "Aviso",
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Pega o ID (está na coluna 0 da tabela)
    int id = (int) tblJogos.getValueAt(row, 0);
    String nome = (String) tblJogos.getValueAt(row, 1);

    int opt = javax.swing.JOptionPane.showConfirmDialog(this,
        "Tem certeza que deseja excluir o jogo \"" + nome + "\"?",
        "Confirmar Exclusão", javax.swing.JOptionPane.YES_NO_OPTION);

    if (opt == javax.swing.JOptionPane.YES_OPTION) {
        try {
            // Chama o DAO para deletar do banco
            jogoDAO.excluir(id);
            
            javax.swing.JOptionPane.showMessageDialog(this, "Jogo removido com sucesso!");
            
            // Recarrega a tabela para sumir da tela
            carregarJogos();
            
        } catch (SQLException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Erro ao excluir no banco: " + ex.getMessage(), "Erro", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    }//GEN-LAST:event_btnExcluirActionPerformed

    
        private void onSelect() {
        int row = tblJogos.getSelectedRow();
        if (row >= 0) {
            java.util.List<model.Jogo> jogos = util.DataStore.getInstance().getJogos();
            if (row < jogos.size()) jogoSelecionado = jogos.get(row);
        }
    }

    public void carregarJogos() {
    javax.swing.table.DefaultTableModel mdl = (javax.swing.table.DefaultTableModel) tblJogos.getModel();
    mdl.setRowCount(0);
    
    try {
        // Agora busca do banco de dados!
        java.util.List<model.Jogo> lista = jogoDAO.listarTodos(); 
        
        for (model.Jogo j : lista) {
            mdl.addRow(new Object[]{
                j.getId(), 
                j.getNome(), 
                j.getPlataforma(),
                j.getAno(), 
                j.getValorAluguel(),
                j.getQuantidadeEstoque(), 
                j.getDiasAluguelPadrao()
            });
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar: " + e.getMessage());
    }
}   
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JScrollPane scrJogos;
    private javax.swing.JTable tblJogos;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtDias;
    private javax.swing.JTextField txtEstoque;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPlataforma;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
